#!/usr/bin/env bash
# shellcheck shell=bash
# =============================================================================
# setup-nanobot.sh — Install Nanobot
# =============================================================================
#
# Description:
#   Sets up the nanobot environment by cloning the repository, building Docker
#   images, and initializing the nanobot container.
#
# Environment Variables (optional):
#   NANOBOT_TARGET_REPO_DIRECTORY - Clone destination (default: $HOME/nanobot)
#
# Usage:
#   ./setup-nanobot.sh
#   NANOBOT_TARGET_REPO_DIRECTORY=/opt/nanobot ./setup-nanobot.sh
# =============================================================================

set -euo pipefail

# Determine script directory and source shared library
SCRIPT_REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
LIB_PATH="$(realpath "${SCRIPT_REPO_DIR}/../lib/helpers.sh")"

# shellcheck disable=SC1090
source "${LIB_PATH}" || {
  echo "[ERROR] Shared library not found: ${LIB_PATH}" >&2
  exit 1
}

# Configuration
: "${NANOBOT_TARGET_REPO_DIRECTORY:=$HOME/nanobot}"
NANOBOT_SHARED_DIRECTORY="$HOME/.nanobot"
DOCKERFILE_EXTEND_SRC="${SCRIPT_REPO_DIR}/../templates/nanobot/Dockerfile.extend"

# =============================================================================
# Main
# =============================================================================

step "Setting up Nanobot"

# Pre-flight
if ! command -v docker &>/dev/null; then
  error "Docker is not installed. Please install Docker first."
fi

success "Docker is available"

# Clone or update repository
if [[ ! -d "${NANOBOT_TARGET_REPO_DIRECTORY}" ]]; then
  step "Cloning nanobot repository"
  git clone https://github.com/HKUDS/nanobot "${NANOBOT_TARGET_REPO_DIRECTORY}"
else
  step "Updating existing nanobot repository"
  git -C "${NANOBOT_TARGET_REPO_DIRECTORY}" fetch --tags
fi

# Checkout latest tag
LATEST_TAG=$(git -C "${NANOBOT_TARGET_REPO_DIRECTORY}" describe --tags \
  "$(git -C "${NANOBOT_TARGET_REPO_DIRECTORY}" rev-list --tags --max-count=1)")
info "Checking out: ${LATEST_TAG}"
git -C "${NANOBOT_TARGET_REPO_DIRECTORY}" checkout "${LATEST_TAG}"

pushd "${NANOBOT_TARGET_REPO_DIRECTORY}"

# Create restart script
step "Creating restart script"
cat > restart_nanobot.sh << 'RESTART_EOF'
#!/bin/bash
set -e

REBUILD=false
for arg in "$@"; do
  [[ "$arg" == "--rebuild" ]] && REBUILD=true
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

if [[ "$REBUILD" == true ]]; then
  echo "Rebuilding nanobot image ..."
  docker build -t nanobot .

  echo "Rebuilding nanobot-extended image ..."
  docker build -f Dockerfile.extend -t nanobot-extended .
fi

echo "Restarting nanobot gateway ..."
docker compose down nanobot-gateway
docker compose up -d nanobot-gateway
RESTART_EOF

chmod +x restart_nanobot.sh

# Build images
step "Building nanobot Docker image"
docker build -t nanobot .

# Copy Dockerfile.extend
if [[ ! -f "${DOCKERFILE_EXTEND_SRC}" ]]; then
  error "Dockerfile.extend not found at ${DOCKERFILE_EXTEND_SRC}"
fi
info "Copying Dockerfile.extend"
cp "${DOCKERFILE_EXTEND_SRC}" Dockerfile.extend

step "Building nanobot-extended image"
docker build -f Dockerfile.extend -t nanobot-extended .

# Write docker-compose.override.yml
step "Writing docker-compose.override.yml"
cat > docker-compose.override.yml << 'COMPOSE_EOF'
# Auto-generated by setup-nanobot.sh
services:
  nanobot-gateway:
    image: nanobot-extended
    build: {}
  nanobot-cli:
    image: nanobot-extended
    build: {}
COMPOSE_EOF

# Initialize
step "Initializing nanobot"
docker compose run --rm nanobot-cli onboard

popd

# Summary
echo ""
echo -e "${BOLD}═══════════════════════════════════════════════════${RESET}"
success "Nanobot setup complete!"
echo -e "${BOLD}═══════════════════════════════════════════════════${RESET}"
echo ""
echo "Source:     ${NANOBOT_TARGET_REPO_DIRECTORY}"
echo "Config:     ${NANOBOT_SHARED_DIRECTORY}/config.json"
echo ""
echo "Next steps:"
echo "  cd ${NANOBOT_TARGET_REPO_DIRECTORY}"
echo "  ./restart_nanobot.sh"
echo ""
echo "Test:"
echo "  docker compose -f ${NANOBOT_TARGET_REPO_DIRECTORY}/docker-compose.yml run --rm nanobot-cli agent -m 'Hello!'"